FROM envoyproxy/envoy:v1.32.1

# Installing envsubst, used at the custom 'docker-entrypoint.sh'
RUN apt-get update && apt-get install gettext-base

COPY ./template.envoy.yaml /etc/envoy/envoy.yaml.template

COPY ./docker-entrypoint.sh /

RUN chmod +rx /docker-entrypoint.sh

EXPOSE $ENVOY_SERVER_PORT $ENVOY_ADMIN_PORT

# Already set on parent image, written here for clarity
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["envoy", "-c", "/etc/envoy/envoy.yaml"]