version: "3.8"
services:

  extauthz-service:
    build:
      context: ./extauthz-service
      args:
        - PACKAGE_NAME=extauthz-service
        - SERVER_PORT=${EXT_AUTH_Z_PORT}
        - RELEASE_BUILD=${RELEASE_BUILD}
    image: ${DOCKER_REGISTRY}/extauthz-rust.extauthz-service:latest
    container_name: extauthz-rust.extauthz-service
    ports:
      - "8080:${EXT_AUTH_Z_PORT}"
    environment:
      - SERVER_PORT=${EXT_AUTH_Z_PORT}
    networks:
      - extauthz_net

  nginx:
    build:
      context: ./nginx
      args:
        - SERVER_PORT=${NGINX_SERVER_PORT}
    image: ${DOCKER_REGISTRY}/extauthz-rust.nginx:latest
    container_name: extauthz-rust.nginx
    environment:
      - SERVER_PORT=${NGINX_SERVER_PORT}
      - SERVER_NAME=${NGINX_SERVER_NAME}
    networks:
      - nginx_net

  envoy:
    build:
      context: ./envoy
      args:
        - SERVER_PORT=${ENVOY_SERVER_PORT}
        - ADMIN_PORT=${ENVOY_ADMIN_PORT}
    image: ${DOCKER_REGISTRY}/extauthz-rust.envoy:latest
    container_name: extauthz-rust.envoy
    ports:
      - "80:${ENVOY_SERVER_PORT}"
      # - "8080:${ENVOY_ADMIN_PORT}"
    environment:
      - SERVER_PORT=${ENVOY_SERVER_PORT}
      - ADMIN_PORT=${ENVOY_ADMIN_PORT}
      - NGINX_SERVER_PORT=${NGINX_SERVER_PORT}
      - NGINX_SERVER_ADDRESS=nginx
    depends_on:
      - nginx
    networks:
      - extauthz_net
      - nginx_net
      - internet

networks:
  extauthz_net:
    driver: bridge
    internal: true
  nginx_net:
    driver: bridge
    internal: true
  internet:
    driver: bridge