[package]
authors = ["Rafael Lemos <contact@flemosr.com"]
name = "extauthz"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
envoy-types = "0.3"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tonic = "0.10.2"
