[package]
authors = ["Rafael Lemos <contact@flemosr.com"]
name = "extauthz"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
envoy-types = "0.5.4"
tokio = { version = "1.41", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.3"
