FROM rust:1.86.0-slim-bookworm AS builder

WORKDIR /usr/src

# Create blank project, copy cargo files and make a dummy build to download deps
RUN cargo new app

WORKDIR /usr/src/app

COPY Cargo.toml ./

RUN cargo build

RUN rm ./src/*

RUN rm -rf ./target

# Copy actual src files and build the app
COPY src ./src/

ARG RELEASE_BUILD

# If $RELEASE_BUILD is set, set BUILD_FLAG as '--release', or leave it empty
ENV BUILD_FLAG=${RELEASE_BUILD:+"--release"}

RUN cargo build $BUILD_FLAG

# Create runtime image

FROM debian:bookworm-slim AS runtime

# Should be overwritten by docker-compose.yaml

ARG PACKAGE_NAME

ARG RELEASE_BUILD

# If $RELEASE_BUILD is set, set TARGET_FOLDER as 'release', or set it as 'debug'
ENV TARGET_FOLDER=${RELEASE_BUILD:+release}
ENV TARGET_FOLDER=${TARGET_FOLDER:-debug}

COPY --from=builder /usr/src/app/target/$TARGET_FOLDER/$PACKAGE_NAME /usr/local/bin

# Should be overwritten by docker-compose.yaml
ARG SERVER_PORT

EXPOSE $SERVER_PORT

ENV BIN_NAME=$PACKAGE_NAME

CMD /usr/local/bin/${BIN_NAME}
